version: '3.8'

services:
  payment-service:
    build: .
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_USERNAME=root
      - DB_PASSWORD=password
    depends_on:
      - mysql-db
    networks:
      - ecommerce-network

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: payment_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ecommerce-network

volumes:
  mysql_data:

networks:
  ecommerce-network:
    driver: bridge
