server:
  port: 8082

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Piyu$777*

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  jackson:
    serialization:
      write-dates-as-timestamps: false

  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 100

logging:
  level:
    com.ecommerce.paymentservice: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

payment:
  gateways:
    stripe:
      enabled: true
      api-key: sk_test_dummy_key
    paypal:
      enabled: true
      client-id: dummy_client_id
      client-secret: dummy_client_secret
